### ISSUE TITLE
Change labels for export buttons

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/mdn-bcd-collector#811]
We see quite a few PRs every week created by accident, e.g. https://github.com/openwebdocs/mdn-bcd-results/pull/878

Should we remove this feature?
What's the use case?

**Comment by queengooborg** [comment]
Before the Selenium script was introduced, this function used to be the only way to get the results from multiple browsers into GitHub, since I would have to manually run every browser version on BrowserStack, one by one.  However, since the Selenium script does most of the work for us, this is only important for a few browsers (Safari and mobile browsers) that we can't automatically test with using Selenium.

However, we do unfortunately get a lot of PRs opened from random users clicking on the GitHub export, and it would be great to limit who is allowed to export to GitHub.  I was thinking of ensuring that it can only be category-level or higher.  Maybe some private passkey that must be entered, so only we can generate these PRs?

**Comment by foolip** [comment]
The original motivation for this was to make it very easy to collect results even from browsers and devices where we can't save files or otherwise get data out of the browser, like old mobile browsers running through an emulator. I think keeping that capability is useful.

Changing the name of the button would be a good start I think. Originally I think this was the only way to export results, even before there was a way to download, so that explains the generic wording.

Are PRs against mdn-bcd-results used at all in the current day-to-day work? If not, automatically closing any PR might be an option. A maintainer could reopen and merge anything that was intentional.

**Comment by Elchi3** [comment]
I've sent https://github.com/openwebdocs/mdn-bcd-collector/pull/902
