### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by MrBrain295** [openwebdocs/mdn-bcd-collector#849]
The Nu HTML checker gives a few errors on this site. [Here](https://validator.nu/?doc=https%3A%2F%2Fmdn-bcd-collector.gooborg.com%2F) is the link to the errors.

**Comment by queengooborg** [comment]
Thanks for the report.  I pushed https://github.com/openwebdocs/mdn-bcd-collector/commit/f9ca02767dd499479a8d6ea205e0aec6559b4fcb to fix the issues regarding the `class` duplication.  The other two errors, however, I believe can be safely ignored because:

- The first error is stating that "Attribute media not allowed on element [meta](https://html.spec.whatwg.org/multipage/#the-meta-element) at this point."  This is an inaccurate statement, and the error even mentions the list of available attributes, which includes `media`.  Not to mention, our implementation matches the [spec's example](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color).
- The second error states that one of our labels must be for a non-hidden form control.  The form control that it refers to, `limitExposure`, is programmatically hidden and unhidden along with the label, but it is visible by default.
